# Basic List

print('Basic List')
data = ['Python', 'C#', 'C++', 'HTML5']

print('data: ', data)
print('type: ', type(data))
print('amount: ', len(data))
print('data[0]: ', data[0])
print('data[1]: ', data[1])
print('data[2]: ', data[2])
print('data[3]: ', data[3])
print('--------------------')

print('Find list by in and not in')
print('ReactJS' in data)
print('Python' in data)
print('Golang' not in data)
print('--------------------')

print('List and range')
print('data[0:]', data[0:])
print('data[:2]', data[:2])
print('data[0:3]', data[0:3])
print('--------------------')

print('Add new data to list')
print('Add new data to list by append()') # ต่อท้าย
data.append('ASP.NET Core MVC')
print('data: ', data)
print('type: ', type(data))
print('amount: ', len(data))
print('data[0]: ', data[0])
print('data[1]: ', data[1])
print('data[2]: ', data[2])
print('data[3]: ', data[3])
print('data[4]: ', data[4])
print('\n')

print('Add new data to list by insert()') # ระบุตำแหน่งที่แทรก
data.insert(0, 'Golang')
print('data: ', data)
print('type: ', type(data))
print('amount: ', len(data))
print('data[0]: ', data[0])
print('data[1]: ', data[1])
print('data[2]: ', data[2])
print('data[3]: ', data[3])
print('data[4]: ', data[4])
print('data[5]: ', data[5])
print('\n')

print('Add new data to list by +') # รวม list เข้าด้วยกัน
data += ['Angular', 'ReactJS']
print('data: ', data)
print('type: ', type(data))
print('amount: ', len(data))
print('data[0]: ', data[0])
print('data[1]: ', data[1])
print('data[2]: ', data[2])
print('data[3]: ', data[3])
print('data[4]: ', data[4])
print('data[5]: ', data[5])
print('data[6]: ', data[6])
print('data[7]: ', data[7])
print('\n')

print('Add new data to list by extend()') # ขยาย/แตกข้อมูลก่อนเพิ่มใน list
data.extend('JAVA')
print('data: ', data)
print('type: ', type(data))
print('amount: ', len(data))
print('data[0]: ', data[0])
print('data[1]: ', data[1])
print('data[2]: ', data[2])
print('data[3]: ', data[3])
print('data[4]: ', data[4])
print('data[5]: ', data[5])
print('data[6]: ', data[6])
print('data[7]: ', data[7])
print('data[8]: ', data[8])
print('data[9]: ', data[9])
print('data[10]: ', data[10])
print('data[11]: ', data[11])
print('--------------------')

print('Remove data from list')
print('Remove data from list by remove()')
data.remove('J')
data.remove('A')
data.remove('V')
data.remove('A')
print('data: ', data)
print('type: ', type(data))
print('amount: ', len(data))
print('data[0]: ', data[0])
print('data[1]: ', data[1])
print('data[2]: ', data[2])
print('data[3]: ', data[3])
print('data[4]: ', data[4])
print('data[5]: ', data[5])
print('data[6]: ', data[6])
print('data[7]: ', data[7])
print('\n')

print('Remove data from list by del')
del data[0]
print('data: ', data)
print('type: ', type(data))
print('amount: ', len(data))
print('data[0]: ', data[0])
print('data[1]: ', data[1])
print('data[2]: ', data[2])
print('data[3]: ', data[3])
print('data[4]: ', data[4])
print('data[5]: ', data[5])
print('data[6]: ', data[6])
print('--------------------')

print('Sorting data by sort()')
print('Before sorting: ', data)
data.sort()
print('After sorting: ', data)
data.sort(reverse=True)
print('After sorting (reverse): ', data)
print('--------------------')



